# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Set plugins
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-commonmark
  - jekyll-include-cache
  - jemoji
  - jekyll-remote-theme
  - jekyll-compress-html
  - jekyll-assets
  - jekyll-minifier

# Site settings
url: 'https://nimarak.github.io/'
baseurl: ''
title: 'My website'
description: 'This is my new website'
permalink: pretty
logo: "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c?s=52"
lang: en
author:
  name: Nikolaos Marakis  
  email: nik.marakis@gmail.com

# SEO settings
social:
  name: Nikolaos MArakis  # The name associated with social profiles
  links:
    - https://www.linkedin.com/in/nikolaos-marakis/  # LinkedIn profile URL
    - https://github.com/nimarak  # GitHub profile URL

# Pagination settings
paginate: 5  # Number of posts to display per page
paginate_path: /blog/page:num/  # URL structure for paginated pages

# Header navigation menu
navigation_header:
  - title: Home
    url: /  # URL for the home page
  - title: About
    url: /about/  # URL for the about page
  - title: Projects
    url: /projects/  # URL for the projects page
  - title: Contact
    url: /contact/  # URL for the contact page
  - title: Blog
    url: /blog/  # URL for the blog page

# Footer navigation menu
navigation_footer:
  - title: Back to top
    url: "#top"  # Anchor link to scroll to top of page
  - title: Projects
    url: /projects/  # URL for the privacy policy page

# Define collections (groups of related content)
collections:
  posts:
    title: Posts
    output: true  # Generate a page for each document in this collection
    description: "My thoughts and ideas"
    feature_image: "https://picsum.photos/2560/600?image=2"  # Header image for posts
  contact:
    title: Contact
    output: true
    description: "Find me here"
    feature_image: "https://picsum.photos/2560/600?image=4"  # Header image for contact page
  projects:
    title: Projects
    output: true
    description: "My projects"
    feature_image: "https://picsum.photos/2560/600?image=6"  # Header image for projects page

# Default settings for collections
defaults:
  - scope:
      path: ""  # Apply to all files in the project
      type: "posts"  # Apply only to posts
    values:
      layout: post  # Use 'post' layout for all posts
      comments: true  # Enable comments for all posts
      share: true  # Enable social sharing for all posts
  - scope:
      path: ""
      type: "pages"  # Apply to all pages
    values:
      layout: page  # Use 'page' layout for all pages
  - scope:
      path: ""
      type: "contact"  # Apply to contact collection
    values:
      layout: contact  # Use 'contact' layout for contact pages
  - scope:
      path: ""
      type: "projects"  # Apply to projects collection
    values:
      layout: project  # Use 'project' layout for project pages

# HTML compression settings
compress_html:
  clippings: all  # Remove all blank space around HTML tags
  comments: ["<!-- ", " -->"]  # Preserve these comment types
  endings: all  # Remove all blank space at the end of HTML elements
  ignore:
    envs: [local]  # Don't compress HTML in local environment
  blanklines: false  # Remove blank lines
  profile: false  # Don't add a timestamp comment
  startings: [html, head, body]  # Remove space after these elements

# Asset optimization settings
assets:
  compression: true  # Enable asset compression
  gzip: true  # Enable gzip compression for assets

# Additional site-wide settings
markdown: kramdown  # Use kramdown as the Markdown processor
highlighter: rouge  # Use rouge for syntax highlighting
sass:
  style: compressed  # Compress CSS output

# Time zone setting
timezone: UTC  # Set the site's time zone to Coordinated Universal Time
